### PR TITLE
update app dependencies

### PR DESCRIPTION
**Pull request by ErfiDev**
hey bro, I updated application dependencies, and some files and codes, if not a problem, please merge it thank

### CODE REVIEW

**Review by Harry-027 — COMMENTED** [review]
Hey @ErfiDev  👋🏻, 

Thanks for the contribution! Could you add .vscode settings to gitIgnore ? Since these are specific to an IDE we might not want them to be part of actual repository.

**Comment by ErfiDev** [comment]
oh sorry... ok

**Comment by ErfiDev** [comment]
updated bro

**Review by Harry-027 — APPROVED** [review]
Looks good to me. Thanks for your contribution :)

**Pull request merged**
